# Generated by Django 4.2 on 2023-04-12 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0002_company_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('model', models.CharField(max_length=150)),
                ('company', models.CharField(max_length=150)),
            ],
        ),
    ]
