# Generated by Django 4.2 on 2023-04-12 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0003_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_date', models.DateField(auto_now=True)),
                ('return_date', models.DateField()),
                ('condition_out', models.CharField(max_length=150)),
                ('condition_return', models.CharField(max_length=150)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='track.device')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='track.employee')),
            ],
        ),
    ]
