# Generated by Django 4.2 on 2023-04-12 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0004_checkout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='condition_return',
        ),
        migrations.CreateModel(
            name='DeviceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_return', models.CharField(max_length=150)),
                ('checkout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='track.checkout')),
            ],
        ),
    ]
